services:
  - type: web
    name: facu-demo-f1
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    healthCheckPath: /facu-demo/health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SCRIPT_NAME
        value: /facu-demo
      - key: REMOTE_STATE_SYNC
        value: true
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
